### ISSUE TITLE
Not every check-in shows up in the database

### ISSUE THREAD

**Issue by missmaggiemo** [missmaggiemo/mcs_registration#75]
We've been having an issue where the number of class check-ins in the web app DB doesn't match the number of credit card charges that would indicate class check-ins.

Things that could possibly be creating this:
1. The web UI view for the number of class checkins (example: https://mcs-registration.firebaseapp.com/admin/dance?uid=2dffd5f9-91f7-3be5-a81b-a63a82459a30) isn't showing accurate data.
2. The act of checking into a class through the web UI (check-in form: https://mcs-registration.firebaseapp.com/class-checkin) doesn't always get committed to the DB.
3. People don't always use the web UI on the tablet to check in.

Solutions:
* Code-based:
- [ ] Add a spinner to the web UI view for class/dance data so that you can't see the class data until it's fully loaded.
- [ ] Add a spinner to the web UI for class check-ins so that users can't fill out the form until the user drop-down is loaded. (Hypothesis: if the user autocomplete hasn't loaded, this is indicative of a connection issue of a particular tablet, and a login at that time won't register in the system.)

* Not code based:
- [x] Volunteers check students and dancers into the event-- no more self-check-in.
- [ ] Check that the post-check-in confirmation doesn't show up until the data is committed to the database.

**Comment by missmaggiemo** [comment]
I do think this is a data connectivity issue between the tablets, the wifi router, and the web app. Recently, I asked the volunteers to use my laptops tethered to my phone to check people in instead of having them check themselves in on the tablets, and the number of check-ins per dance have increased considerably. I'm going to keep doing this, only using the tablets to have people fill out the new student forms.

Further steps:

- [ ] Upgrade the wifi router

- [ ] Add a spinner to the web UI view for class/dance data so that you can't check in until the class data is fully loaded.

- [ ] Add a spinner to the web UI for class check-ins so that users can't fill out the form until the user drop-down is loaded. (Hypothesis: if the user autocomplete hasn't loaded, this is indicative of a connection issue of a particular tablet, and a login at that time won't register in the system.)

**Comment by jmrgibson** [comment]
I dunno how much logic you can do with front end stuff, wouldn't having an
outgoing message queue that opportunistically posts stuff to the server
when it regains connectivity be a more robust and user friendly solution?

**Comment by missmaggiemo** [comment]
I think this has been mostly resolved by behavioral changes, so I'm going to close this!
